spring.application.name=auth-service
server.port = 8081

# Force the microservice to query the cloud config vault for security keys/db strings
spring.config.import=optional:configserver:http://localhost:8888
