
USERNAME_ALREADY_TAKEN=the username you selected is already taken inside this organization workspace. please try another one.
INVALID_CREDENTIALS=the credentials you provided are invalid or do not match this specific workspace company profile.
FIELD_VALIDATION_ERROR=provided form validation input parameter constraints have failed verification requirements.